### ISSUE TITLE
add documentation from Gramadóir website 

### ISSUE THREAD

**Issue by jowagner** [kscanne/gramadoir#2]
The Gramadóir website hosted by SLU seems to be gone. Essential documentation should be added to this repo. If source files are unavailable, documentation can be harvested from the wayback machine, e.g. https://web.archive.org/web/20180211015917/http://borel.slu.edu/gramadoir/

Changing the readme link to the above link may also be a good intermediate workaround.

**Comment by kscanne** [comment]
Hi Joachim, thanks for catching this. Everything moved to cadhan.com 3-4 years ago... I just updated the link in the README and will have a look for more stray borel.slu.edu links in the rest of the documentation.
